### ISSUE TITLE
helm repo add chart-name https://private-repository.company.com --username <user>--password <pass>

### ISSUE THREAD

**Issue by ranjan2829** [komodorio/helm-dashboard#223] opened 2023-02-26 09:18 UTC
### Description

> With the following cmd, you can add easily a protected repository to your charts.
> 
> `helm repo add chart-name https://private-repository.company.com --username <user>--password <pass>`
> 
> However, it's not possible through the helm-dashboard. Please consider adding this feature.

**Comment by undera** [comment] 2023-02-26 09:37
It's a duplicate of #222

**Closed by undera** 2023-02-26 09:38 UTC
