### ISSUE TITLE
Allow overriding local interface

### ISSUE THREAD

**Issue by sphr2k** [komodorio/helm-dashboard#97] opened 2022-11-12 15:11 UTC
It would be nice if it were possible to specify the local interface, e.g. when the cluster is accessed from a headless system

```
helm dashboard --address 0.0.0.0
```

**Comment by undera** [comment] 2022-11-12 16:41
This is a duplicate of #75 

Note that currently you can achieve that via HD_BIND environment variable

**Closed** 2022-11-12 16:42 UTC
