### ISSUE TITLE
When add new repo, i got this error message "Error: unknown flag: --time-format" 

### ISSUE THREAD

**Issue by kenchen1101** [komodorio/helm-dashboard#117] opened 2022-11-25 07:46 UTC
![image](https://user-images.githubusercontent.com/9885352/203927848-10516c4e-c3fd-4615-a7b9-7588cd4e0c01.png)

When add new repo, i got this error message "Error: unknown flag: --time-format" 

PS: My helm verion as below: 

version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

**Comment by kenchen1101** [comment] 2022-11-25 07:47
helm dashboard is v0.2.8

**Comment by kenchen1101** [comment] 2022-11-25 08:17
hem chart repo image:
ghcr.io/helm/chartmuseum:v0.15.0

**Comment by undera** [comment] 2022-11-25 08:20
This is a duplicate of #36

**Closed by undera** 2022-11-25 08:20 UTC
